### ISSUE TITLE
Using dotnet core

### ISSUE THREAD

**Issue by mikkeljohnsen** [mono/mono.posix#12]
Hi

I'm trying to change my project from Mono to dotnet on Linux, Windows and macOS.

I get this error on Linux:

```
Unable to load shared library 'intl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libintl: kan ikke åbne delt objektfil: Ingen sådan fil eller filkatalog
   at Mono.Unix.Catalog.bindtextdomain(IntPtr domainname, IntPtr dirname)
   at Mono.Unix.Catalog.Init(String package, String localedir)
```

Why is the DLL not referencing the correct files on the OS ?

dotnet can not use the "Mono.Unix.dll.config" file. So how is this going to work ?

**Comment by mikkeljohnsen** [comment]
If I rename "libMono.Unix.so" to "libintl.so" it works. Is that the intention ?

**Comment by tsuckow** [comment]
That sounds like you might be trying to use a platform with an incompatible build of libc. What linux distro is it?

**Comment by Gzushgshsh** [comment]
> That sounds like you might be trying to use a platform with an incompatible build of libc. What linux distro is it?

I had the same problem, I notice that the solution of the person who made this issue only interferes in the execution of the program, the intenationalization does not work at all. 
I'm using MX-Linux 23. I couldn't find the libintl.so library on the system, I only found this other file:
![image](https://github.com/mono/mono.posix/assets/95548091/3c3623b0-19f2-4c43-bd12-c92a3f8da134)
