### ISSUE TITLE
Can't run Mono.Posix on alpine docker

### ISSUE THREAD

**Issue by tomer-amir-apiiro** [mono/mono.posix#18]
I tried using this lib running a `net6.0` app on an alpine docker container, but it seems to fail on the following error:

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'Mono.Unix' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libMono.Unix: No such file or directory
   at Mono.Unix.Native.Syscall.stat(String file_name, Stat& buf)
   at Mono.Unix.UnixFileSystemInfo.GetFileStatus(String path, Stat& stat)
   at Mono.Unix.UnixFileSystemInfo.Refresh(Boolean force)
   at Mono.Unix.UnixFileSystemInfo..ctor(String path)
   at Mono.Unix.UnixFileInfo..ctor(String path)
   at Program.<Main>$(String[] args) in /code/Program.cs:line 3

```

Running the same code on a Debian container seems to work.

My code:

```csharp
using Mono.Unix;

var test = new UnixFileInfo("/tmp");
Console.WriteLine(test);
```

Here is a repo that can help reproduce the issue: https://github.com/tomer-amir/mono-alpine-demo

Am I missing something?

**Comment by nsobiratel** [comment]
i found root problem and possible workaround. when i build my project, output dir doesn't contain file Mono.Unix.dll.config. it placement in nuget package or nuget cache %user%\.nuget\packages\mono.unix\7.1.0-final.1.21458.1\lib\net6.0\Mono.Unix.dll.config. When i include this file into my project and set None action on build + copy to output dir - my binary file successfully run on system, where crashed before (centos based systems)
